import Head from 'next/head'

// Components
import LoadingScreen from '../components/LoadingScreen/LoadingScreen'

export default function Home() {
  return (
    <>
      <Head>
        <title>PRSNA Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoadingScreen
        prsna_Logo_LoadingScreen="https://anima-uploads.s3.amazonaws.com/projects/6215578908245f0a14cf0140/releases/62155a0fd98caca3fa3450ab/img/prsna-logo-loading-screen-2@2x.png"
        loadingBarImg="https://anima-uploads.s3.amazonaws.com/projects/6215578908245f0a14cf0140/releases/62155a0fd98caca3fa3450ab/img/group-44-2@2x.png"
        percent="100%"
        spanText2="welcome"
        spanText3="welcome"
      />
    </>
  )
}
